### ISSUE TITLE
Pipeline unsupported version

### ISSUE THREAD

**Issue by gammelgaard52** [microsoft/Dynamics365-Xpp-Samples-Tools#1]
I get the error, that the pipeline is of an unsupported version of product - any ideas or someone who can export a new? This is the one I try to import: https://bit.ly/3fwizHd

Error:
The exported JSON is not valid or is not compatible with the current product version. Try exporting and importing again.

https://i.imgur.com/wvKAKX7.jpg

**Comment by jorisdg** [comment]
Where are you trying to import it? I tried it again just now and it works perfectly on Azure DevOps. Are you using Azure DevOps Server (aka "on prem") maybe?
Otherwise, can you make sure the JSON you downloaded is not corrupted or somehow became invalid?

**Comment by gammelgaard52** [comment]
I use the Azure DevOps, go to my build pipelines and using the pipeline import wizard: https://i.imgur.com/MFD0g29.jpg
Also, I download the .json file from in here https://bit.ly/3fwizHd and trying to import that one.

**Comment by jorisdg** [comment]
Can you review the contents of the JSON file after you downloaded? I expect that the way you grab it from GitHub is causing the issue. If you open the file in Notepad you should be able to identify what's wrong.

**Comment by gammelgaard52** [comment]
Yep, you are right. Something happend to the file when downloaded - at least it certainly look strange.
https://i.imgur.com/LTfbnDU.jpg (zoom in at the picture to see details)

**Comment by gammelgaard52** [comment]
Okay, so solution was to download it with internet explorer. I tried at first with Google Chrome, but it tampered with the file on download for some reason.
Thanks @jorisdg for pointing out, that the file might have been altered.
