### ISSUE TITLE
xpp-classic-ci.ps1 fails

### ISSUE THREAD

**Issue by simonefinotti** [microsoft/Dynamics365-Xpp-Samples-Tools#3]
When executing .\xpp-classic-ci.ps1 the scripts fails:

`Get-Content : Cannot find path 'C:\Users\Administrator\Desktop\classic-ci.json' because it does not exist.`

I suppose it looks for xpp-classic-ci.json, otherwise it's not clear to me what it's looking for.

**Comment by jorisdg** [comment]
You're absolute right. This happened due to a file rename. I changed it now.
